CREATE DATABASE MaraphoneSkills;

USE MaraphoneSkills
GO

CREATE TABLE Runner
(
	ID		INT IDENTITY PRIMARY KEY,
	[Email]		VARCHAR(150)	NOT NULL,
	[Password]	NVARCHAR(40)	NOT NULL,
	[Name]		NVARCHAR(150)	NOT NULL,
	[Surname]	NVARCHAR(150)	NOT NULL,
	[Sex]		NVARCHAR(20)	NOT NULL,
	[ImageName]	NVARCHAR(150)	NOT NULL,
	[Image]		IMAGE		NOT NULL,
	[Country]	NVARCHAR(150)	NOT NULL
)
GO
